### ISSUE TITLE
Installation Failed (Pdx213)

### ISSUE THREAD

**Issue by Alpha-Point** [lufeidotcom/Xperia-10-III-GA-Remapper#1]
Hi. I have a Sony Xperia 10 III (xq-bt52), which is referenced as the PDX-213.
After having Magisk up and running, I tried to install the module, but I get the following error:

- Copying zip to temp directory
- Installing pdx213_ga_remapper.zip
- Current boot slot: _b
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
**********************************
 Xperia 10 III GA Button Remapper 
 by lufei 
**********************************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
  inflating: module.prop
   creating: system/
   creating: system/vendor/
   creating: system/vendor/usr/
   creating: system/vendor/usr/keylayout/
  inflating: system/vendor/usr/keylayout/gpio-keys.kl
- Extracting module files
This module is meant for Xperia 10 III (Pdx213)
Aborting Module Installation
! Installation failed

I don't know what I'm doing wrong (kind of a noob), but I feel like this should work.
Hope the project isn't defunct and you can help me get the god dang side button to work as a camera button/shutter, as it should (instead of our dear overlords snoop trigger....as if constant mic/cam access wasn't enough).
Thanks

**Comment by jakobfridesjo** [comment]
Try my latest release and if it doesn't work, try installing termux, run `getprop ro.product.device` and give me the result. Your phone might report a different id than mine does and then I could add it

**Comment by Alpha-Point** [comment]
Hi again. I can't thank you enough for your help and taking your time with
this issue.
I did as you said and surprisingly, the product id came back as XQ-BT52.
I'm in Europe (Portugal) and I am unsure if this is a regionalization issue
(I believe this is the global version).
Is there a way to your remapper working (btw, I have looked up the model
name and it seems XQ-BT52 is the model name associated with the codename
PDX 213).
Thank you once again.

A segunda, 11/07/2022, 00:05, lufeidotcom ***@***.***>
escreveu:

**Comment by jakobfridesjo** [comment]
Mine reports pdx213, but I'm also on custom rom (GSI) so that might be why. You can try the new version I've uploaded (v1.2)

**Comment by Alpha-Point** [comment]
Hi, thank you again. Just letting you know that the updated version worked like a charm. There is still some issue with the software recognition. While the button now works, pressing it inside the camera app doesn't really do anything. I feel the vibration and hear the sound as if it was snapping a shot, but nothing ever happens. If I use another camera app, like Open Camera, it works perfectly.
I also tried using the Button Mapper app, to change the behaviour of the button, where it comes up as Camera_27. Again, I can now get long press behaviour to open the Camera app, double click to turn the flashlight on and off, and click to snap photo.
It works, except for snapping photos on the standard camera app. No such issue on the Open Camera app.
BTW, anyway I can donate something for your work/time and the very useful remapper. I mean, you are correcting a mistake Sony made..

**Comment by jakobfridesjo** [comment]
Nice that it worked! I'll be quite busy this fall but if I'll have some time over I'll look into getting the stock camera or maybe gcam working somehow.
Thank you for offering to donate and there's details for that on my main github page, though it's not a big deal since I'm mostly just doing things like these for the fun/challenge

I'll mark this issue as solved but feel free to open another if there's something else that could be improved
